version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5105:5432
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx_development
    volumes:
      - pgdata:/data/postgres
      - ./create_testing_db.sh:/docker-entrypoint-initdb.d/create_testing_db.sh
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/usr/app
      - usr/app/node_modules/bcrypt/

volumes:
  pgdata:
    driver: local
