version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5105:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx_development
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
